version: "3"

services:
  app:
    container_name: app
    image: node:16.13.0
    build: ./app
    volumes:
      - ./app/:/usr/src/app
    tty: true
    command: npm start
    ports:
      - "3000:3000"
    networks:
      - app-network
    restart: "always"
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/scripts/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
