version: "3"

services:
  app:
    container_name: app
    build: ./app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    volumes:
      - ./app/:/usr/src/app
      - /usr/src/app/node_modules
    tty: true
    command: npm start
    networks:
      - app-network
    restart: "always"
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./db/mysql:/var/lib/mysql
      - ./db/scripts/:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=password
    networks:
      - app-network
  nginx:
    container_name: nginx
    build: ./nginx
    restart: always
    depends_on:
      - app
    tty: true
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
